HUCO 25, 36, 37, 38 - User Admin
Hands-Up-Card-Open/HandsUpForServer pull request #2
Opened 2022-04-03 14:01 UTC by icechocola05

### 회원 가입
- name, email, password 값 DB에 넣고 결과 값 전송
### 로그인
- email, password 값 확인 하고 결과와 user_id 전송
### 회원 정보 확인 및 수정
- user_id로 회원 정보 전부 전송
- 회원 정보 수정할 경우 수정 후 결과 값 전송
### 회원 탈퇴
- password 값 확인 후 회원 정보 삭제, 결과 값 전송

2022-04-04 07:08 UTC, sleesm requested changes
authi.js에 있는 로직들이 함수로 묶여서 한 번 더 받아와서 사용하는 것이면 더 좋을 것 같아요!

2022-04-04 07:08 UTC, sleesm commented on main.js
> +    res.status(500).send('Something broke!')
broken.. n 붙여주세요...😄

2022-04-04 07:08 UTC, sleesm commented on routes/auth.js
> +            if(result[0].emailCount == 0) { //check for duplicate email address
이미 있는 사용자 정보를 업데이트하는 것인데 emailCount가 1이어야 하는 것이 아닌가요?

2022-04-04 07:08 UTC, sleesm commented on routes/auth.js
> +                            throw error;
throw error를 하면 밑에 있는 else에 들어가는 것인가요? 🧐🧐

2022-04-04 13:04 UTC, icechocola05 commented on main.js
> +    res.status(500).send('Something broke!')
네 Something broken 으로 수정했습니다

2022-04-04 13:41 UTC, icechocola05 commented on routes/auth.js
> +            if(result[0].emailCount == 0) { //check for duplicate email address
만약 사용자가 이메일 주소를 변경한다면, 기존 사용자와 동일한 email이 있는지 확인하기 위해 작성한 코드였습니다.
회의를 통해 이메일 주소는 변경 불가능 하다는 내용을 공유하였으니, user_id와 email 값을 바탕으로 user_name, user_password 수정할 수 있도록 하겠습니다

2022-04-04 13:42 UTC, icechocola05 commented on routes/auth.js
> +                            throw error;
throw error; 대신에 response.json({ "result": "fail" }); 로 전부 수정하였습니다!

2022-04-04 23:38 UTC, sleesm commented on routes/auth.js
> +                    "user_password": result[0].user_password
user password는 전달하지 않아도 될 것 같습니다!

2022-04-04 23:39 UTC, sleesm commented on routes/auth.js
> +            if(result[0].emailCount == 0) { //check for duplicate email address
아직 코드를 안 바꾼 게 맞나요?

2022-04-05 09:16 UTC, icechocola05 commented on routes/auth.js
> +            if(result[0].emailCount == 0) { //check for duplicate email address
네 수정하고 커밋 했어야 했는데 구조 수정까지 한번에 하는 중입니다..
다음 커밋은 더 쪼개서 하겠습니다

2022-04-06 10:10 UTC, icechocola05 commented on routes/auth.js
> +                    "user_password": result[0].user_password
네! 수정했습니다.

2022-04-07 13:13 UTC, sleesm reviewed
파일명에 대해서 _를 붙이는 것보다 - 나 낙타형으로 사용하는 것이 일반적이지 않나 싶습니다!

2022-04-07 13:13 UTC, sleesm commented on controllers/auth_controller.js
> +    var post = req.body;
왜 변수 이름이 post인지 궁금해요!

2022-04-07 13:13 UTC, sleesm commented on routes/auth.js
> +    authController.getUserPasswordCorrect(req, res).then((respond) => {
왜 이건 함수로 따로 빼지 않고 여기서 계산하는지 궁금합니다

2022-04-08 09:01 UTC, icechocola05 commented on controllers/auth_controller.js
> +    var post = req.body;
body로 수정할까요?

2022-04-08 09:05 UTC, icechocola05 commented on routes/auth.js
> +    authController.getUserPasswordCorrect(req, res).then((respond) => {
비밀번호 확인과 사용자 삭제 부분을 나눠서 작성하려고 하다 보니 그렇게 된 거 같습니다.
컨트롤러로 옮겨서 작성하는 방향으로 수정하겠습니다!

2022-04-08 10:02 UTC, sleesm commented on controllers/auth_controller.js
> +    var post = req.body;
body로 하는건 명확하지 않은 것 같습니다. post에 의미가 들어간다면 그대로 써도 될 것 같습니다

2022-04-08 14:35 UTC, sleesm reviewed
고생 많으셨습니다! 궁금한 점과 주석 관련된 부분 적었습니다! 확인 부탁드려요! 😊😊

2022-04-08 14:35 UTC, sleesm commented on config/db.js
> +// db.connect();
주석 지워주세요!

2022-04-08 14:35 UTC, sleesm commented on controllers/authController.js
> +//for sign in, insert user
주석이 sign up과 sign in이 반대로 된 것 같습니다.

2022-04-08 14:35 UTC, sleesm commented on controllers/authController.js
> +async function postUserInfo(req, res) {
postuserinfo 보다는 createuser 거나 adduser 이런 식으로 하는 건 어떤가요? 명확하게 뭘 위한 것인지 잘 안 보이는 것 같아서요

2022-04-08 14:35 UTC, sleesm commented on controllers/authController.js
> +async function getUserIdByEmail(req, res) {
이것도 sign in을 위한 작업 같은데 주석이 잘못되어 있는 것 같습니다.
그리고 함수명을 getuseridbyemail보다는 sign in 이라든지 뭐 그런 checkuserByEmail 이라든지 명확하게 어떤 함수로 사용되는지 알 수 있도록 사용하는 것이 어떤가요?

2022-04-08 14:35 UTC, sleesm commented on routes/auth.js
> +router.post('/signup',authController.postUserInfo);
req, res를 파라미터로 넘겨주지 않아도 해당 함수들이 잘 실행되나요?

2022-04-10 09:44 UTC, icechocola05 commented on routes/auth.js
> +router.post('/signup',authController.postUserInfo);
네 잘 실행됩니다!

2022-04-10 09:49 UTC, icechocola05 commented on controllers/authController.js
> +async function getUserIdByEmail(req, res) {
네 주석 수정 했습니다! checkUserByEmail 로 수정하겠습니다

2022-04-10 10:40 UTC, icechocola05 commented on controllers/authController.js
> +async function postUserInfo(req, res) {
createUser로 수정했습니다!

2022-04-10 13:20 UTC, sleesm commented
좋아요!!

2022-04-10 13:21 UTC, sleesm approved these changes

2022-04-10 13:21 UTC, merged